---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: observability-operator
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - logging.openshift.io
  resources:
  - clusterlogforwarders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.openshift.io
  resources:
  - clusterloggings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.rhobs
  resources:
  - loggingstacks
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - logging.rhobs
  resources:
  - loggingstacks/finalizers
  - loggingstacks/status
  verbs:
  - get
  - update
- apiGroups:
  - logging.rhobs
  resources:
  - loggingstacks/status
  verbs:
  - get
  - update
- apiGroups:
  - loki.grafana.com
  resources:
  - alertingrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - loki.grafana.com
  resources:
  - lokistacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - loki.grafana.com
  resources:
  - recordingrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - loki.grafana.com
  resources:
  - rulerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.rhobs
  resources:
  - alertmanagers
  - prometheuses
  - servicemonitors
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.rhobs
  resources:
  - monitoringstacks
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - monitoring.rhobs
  resources:
  - monitoringstacks/finalizers
  - monitoringstacks/status
  verbs:
  - get
  - update
- apiGroups:
  - monitoring.rhobs
  resources:
  - monitoringstacks/status
  verbs:
  - get
  - update
- apiGroups:
  - monitoring.rhobs
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.rhobs
  resources:
  - thanosqueriers
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.rhobs
  resources:
  - thanosqueriers/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.rhobs
  resources:
  - thanosqueriers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - operatorgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.openshift.io
  resourceNames:
  - nonroot
  - nonroot-v2
  resources:
  - securitycontextconstraints
  verbs:
  - use
